rails:
  build: .
  restart: always
  env_file: .env.production
  volumes:
    - /home/app/rails/rnplay:/app
    - /home/app/repos:/var/repos
  links:
    - postgres
    - cache
    - redis
  environment:
    RAILS_ENV: production
    VIRTUAL_HOST: rnplay.org,www.rnplay.org

postgres:
  restart: always
  env_file: .env.production
  image: postgres

railsstaging:
  build: .
  restart: always
  env_file: .env.production
  volumes:
    - /home/app/rails/rnplay_staging:/app
    - /home/app/repos:/var/repos
  links:
    - postgres
    - cache
    - redis
  environment:
    RAILS_ENV: staging
    VIRTUAL_HOST: staging.rnplay.org
    PASSENGER_APP_ENV: staging 

postgres:
  restart: always
  env_file: .env.production
  image: postgres

packager042:
  restart: always
  image: "packager:0.4.2"
  env_file: .env.production
  environment:
    VIRTUAL_HOST: packager042.rnplay.org
  volumes:
    - /home/app/rails/rnplay/app_js:/js

packager043:
  restart: always
  image: "packager:0.4.3"
  env_file: .env.production
  environment:
    VIRTUAL_HOST: packager043.rnplay.org
  volumes:
    - /home/app/rails/rnplay/app_js:/js

packager044:
  restart: always
  image: "packager:0.4.4"
  env_file: .env.production
  environment:
    VIRTUAL_HOST: packager044.rnplay.org
  volumes:
    - /home/app/rails/rnplay/app_js:/js

packager060:
  restart: always
  image: "packager:0.6.0"
  env_file: .env.production
  environment:
    VIRTUAL_HOST: packager060.rnplay.org
  volumes:
    - /home/app/rails/rnplay/app_js:/js

packager050:
  restart: always
  image: "packager:0.5.0"
  env_file: .env.production
  environment:
    VIRTUAL_HOST: packager050.rnplay.org
  volumes:
    - /home/app/rails/rnplay/app_js:/js

packager05backports:
  restart: always
  image: "packager:0.5.0"
  env_file: .env.production
  environment:
    VIRTUAL_HOST: packager05backports.rnplay.org
  volumes:
    - /home/app/rails/rnplay/app_js:/js

packagerstaging:
  restart: always
  image: "packager:master"
  env_file: .env.production
  environment:
    VIRTUAL_HOST: packager-staging.rnplay.org
  volumes:
    - /home/app/rails/rnplay_staging/app_js:/js

proxy:
  restart: always
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  environment:
    DEFAULT_HOST: rnplay.org
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /home/app/certs:/etc/nginx/certs
    - /home/app/proxy/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro

redis:
  restart: always
  image: redis

cache:
  restart: always
  image: memcached

worker:
  restart: always
  build: .
  command: bundle exec sidekiq -e production -c 25
  volumes:
    - /home/app/rails/rnplay:/app
  env_file: .env.production
  links:
    - postgres
    - redis
    - cache

logger:
  image: progrium/logspout
  command: syslog://logs.papertrailapp.com:13269
  restart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock

grack:
  image: grack-docker
  volumes:
    - /home/app/repos:/var/repos
    - /home/app/rails/rnplay:/var/rails
  links:
    - postgres
    - /home/app/rails/rnplay:/rails
  environment:
    VIRTUAL_HOST: git.rnplay.org

grackstaging:
  image: grack-docker
  volumes:
    - /home/app/rails/rnplay_staging:/rails
    - /home/app/repos:/var/repos
  links:
    - postgres
  environment:
    VIRTUAL_HOST: git-staging.rnplay.org
